### ISSUE TITLE
How to conduct open-vocabulary 3D search?

### ISSUE THREAD

**Issue by hanxunyu** [pengsongyou/openscene#74]
Thanks for your great work! But I want to know how to conduct 3D object search in this project. It seems that you only provide the function of 3D semantic segmentation but i don't know how to search 3D object by typing prompts. Thanks a lot.

**Comment by pengsongyou** [comment]
One can do the 3D object search in a manual check manner, since as shown in Table 6, there are many newly found objects in the Matterport3D dataset. What we did was simply use our interactive viewer, load all scenes, do the query, and see whether each corresponding highlighted object corresponds to the annotations in GT labels or not.
